for extracting tar file we need to use module called unarchive module

- hosts: nodes
  tasks:
    - name: Install Maven
      get_url:
        url: https://downloads.apache.org/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.tar.gz
        dest: /opt
        mode: '0755'
    - name: extract maven
      unarchive:
        src: /opt/apache-maven-3.8.1-bin.tar.gz
        dest: /opt
        remote_src: True
