---
- hosts: localhost
  tasks:
    - name: install java package
      yum:
        name: java-1.8.0-openjdk-devel
        state: present
    - name:  install git
      yum:
        name: git
        state: latest
